---
name: Release Installer ISO
on: release

env:
  VERSION: 41

jobs:
  release_iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          flatpak_remote_refs_dir: /github/workspace/flatpaks
          image_name: ${{ github.event.repository.name }}
          image_repo: ghcr.io/${{ github.repoistory_owner }}
          iso_name: ${{ github.event.repository.name }}-${{ env.VERSION}}.iso
          variant: xfce
          version: ${{ env.VERSION }}

      - name: Upload ISO as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
