---
name: Release Installer ISO
on:
  release:
    type: created

env:
  VERSION: latest

jobs:
  release_iso:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
        flavor: ["main", "nvidia"]

    steps:
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          flatpak_remote_refs_dir: packages/flatpaks
          image_name: ${{ github.event.repository.name }}-${{ matrix.flavor }}
          image_repo: ghcr.io/${{ steps.registry_case.outputs.lowercase }}

          iso_name: ${{ github.event.repository.name }}-${{ matrix.flavor }}-${{ github.event.release.tag_name }}.iso
          variant: xfce
          version: ${{ env.VERSION }}

      - name: Upload ISO as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
